export const shops = [
  {
    floor: "Ground Floor",
    logo: "/logos/verinno.png",
    phone: ["01222822999"],
    email: "example@mail.com",
    name: "Verinno",
    facebook: "https://www.facebook.com/Verinnofurnitureeg/?locale=ar_AR",
    instagram: "https://www.instagram.com/verinno_furniture/?hl=ar",
    category: [
      "Modern Furniture",
      "Classic Furniture",
      "Lighting",
      " Artificial Plants & Pots",
      "Outdoor Furniture",
    ],
    images: [
      "/shops images/Verinno/6- universale dining room.jpg",
      "/shops images/Verinno/7- sofa seat 7.jpg",
      "/shops images/Verinno/IMG_0006 copy.jpg",
      "/shops images/Verinno/IMG_0013  copy.jpg",
    ],
  },
  {
    floor: "Ground Floor",
    logo: "/logos/American-Furniture.webp",
    phone: ["02-38260366", "19997"],
    email: "example@mail.com",
    name: "American Furniture",
    facebook: "https://www.facebook.com/AmericanFurnitureEgypt/",
    instagram: "https://www.instagram.com/american_furniture_egypt/",
    category: ["Modern Furniture"],
    images: [
      "/shops images/americanfurniture/gris (4).jpg",
      "/shops images/americanfurniture/hawai (1).jpg",
      "/shops images/americanfurniture/marina (4).jpg",
      "/shops images/americanfurniture/new gold (1).jpg",
    ],
  },
  {
    floor: "Ground Floor",
    logo: "/logos/Cotistahl.webp",
    phone: ["01022237672"],
    email: "example@mail.com",
    name: "Contistahl",
    facebook: "https://www.facebook.com/ContistahlGroup/?locale=ar_AR",
    instagram: "https://www.instagram.com/contistahl_group/?hl=ar",
    category: ["Kitchens", "Dressing Rooms"],
    images: [
      "/shops images/Contistahl/IMG_2101 h-R.jpg",
      "/shops images/Contistahl/new shaker.jpg",
      "/shops images/Contistahl/Trend final low.jpg",
      "/shops images/Contistahl/WESTERN.jpg",
    ],
  },
  {
    floor: "Ground Floor",
    logo: "/logos/Cairo-Art-.webp",
    phone: ["01225479978", "01280803335"],
    email: "example@mail.com",
    name: "Cairo Art",
    facebook: "https://www.facebook.com/cairo.art2020/",
    instagram: "",
    category: ["Home Accessories & Decor", "Hand Made"],
    images: [
      "/shops images/Cairo Art/WhatsApp Image 2023-03-21 at 9.03.54 AM.jpeg",
      "/shops images/Cairo Art/WhatsApp Image 2023-03-21 at 9.03.56 AM.jpeg",
      "/shops images/Cairo Art/WhatsApp Image 2023-03-21 at 9.03.57 AM.jpeg",
      "/shops images/Cairo Art/WhatsApp Image 2023-03-21 at 9.03.58 AM (1).jpeg",
    ],
  },
  {
    floor: "Ground Floor",
    logo: "/logos/TEXMAR-LOGO-ENGLISH.webp",
    phone: ["02-38260080", "01211158580"],
    email: "example@mail.com",
    name: "Texmar",
    facebook: "",
    instagram: "",
    category: ["Fabric & Curtains"],
    images: [
      "/shops images/Texmar/16299399_1162084360577030_6833736835422951265_n.jpg",
      "/shops images/Texmar/13567488_969016959883772_4409438782163068140_n.jpg",
      "/shops images/Texmar/13537627_969015906550544_3175867776933860562_n.jpg",
      "/shops images/Texmar/13512233_969016736550461_8949507598340992598_n.jpg",
    ],
  },
  {
    floor: "Ground Floor",
    logo: "/logos/Esque_Artboard 1.webp",
    phone: ["01202400782"],
    email: "example@mail.com",
    name: "Esque",
    facebook: "",
    instagram: "",
    category: ["Modern Furniture"],
    images: [
      "/shops images/Esque/53900-48510 .jpeg",
      "/shops images/Esque/73400- 66060.jpeg",
      "/shops images/Esque/100400-85350.jpeg",
      "/shops images/Esque/140600-119510.jpeg",
    ],
  },
  {
    floor: "Ground Floor",
    logo: "/logos/APEX-logo(1)-1.webp",
    phone: ["01099927451"],
    email: "example@mail.com",
    name: "Apex",
    facebook: "https://www.facebook.com/apex.furniture.1948",
    instagram: "https://www.instagram.com/apex.furniture/?hl=ar",
    category: ["Modern Furniture", "Lighting"],
    images: [
      "/shops images/Apex/002.jpg",
      "/shops images/Apex/004 copy (1).jpg",
      "/shops images/Apex/berly.jpg",
      "/shops images/Apex/Daimond.jpg",
    ],
  },
  {
    floor: "Ground Floor",
    logo: "/logos/Mazloum.png",
    phone: ["19744", "0127266676"],
    email: "example@mail.com",
    name: "Mazloum Home",
    facebook: "https://www.facebook.com/mazloumhome/",
    instagram: "https://www.instagram.com/mazloum_home/?hl=ar",
    category: ["Modern Furniture", "Lighting"],
    images: [
      "/shops images/Mazloum_Home/0093422_portento.jpeg",
      "/shops images/Mazloum_Home/0093428_leggiadro.jpeg",
      "/shops images/Mazloum_Home/ALF.jpeg",
      "/shops images/Mazloum_Home/Mazloum Home 3.jpeg",
    ],
  },
  {
    floor: "Ground Floor",
    logo: "/logos/logo-FB.webp",
    phone: ["01220760333"],
    email: "example@mail.com",
    name: "Tiffany",
    facebook: "https://www.facebook.com/Tiffanylighting/?locale=ar_AR",
    instagram: "https://www.instagram.com/tiffanylightingco/?hl=ar",
    category: ["Lighting"],
    images: [
      "/shops images/Tiffany/WhatsApp Image 2022-08-08 at 8.42.43 AM.jpeg",
      "/shops images/Tiffany/WhatsApp Image 2022-08-08 at 8.43.10 AM (1).jpeg",
      "/shops images/Tiffany/WhatsApp Image 2022-08-08 at 8.43.10 AM (2).jpeg",
      "/shops images/Tiffany/WhatsApp Image 2022-08-08 at 8.43.10 AM (3).jpeg",
    ],
  },
  {
    floor: "Ground Floor",
    logo: "/logos/Artboard 1 copy 10.webp",
    phone: ["01050860030"],
    email: "example@mail.com",
    name: "Asfour Crystal",
    facebook: "https://www.facebook.com/AsfourCrystal/?locale=ar_AR",
    instagram: "https://www.instagram.com/asfourcrystalofficial/?hl=ar",
    category: ["Lighting"],
    images: [
      "/shops images/Asfour/Alabaster/313111-149-21-133.png",
      "/shops images/Asfour/Clay Glue/97_3001_34_24.png",
      "/shops images/Asfour/Empire/31511-248-119-149.png",
      "/shops images/Asfour/Maria Theresa/31111-118-119-105.png",
    ],
  },
  {
    floor: "Ground Floor",
    logo: "/logos/Home_Plus2.webp",
    phone: ["01066600490", "01066600495"],
    email: "example@mail.com",
    name: "Home Plus",
    facebook: "https://www.facebook.com/Homepluseg/photos/?_rdr",
    instagram: "https://www.instagram.com/homepluseg/?hl=ar",
    category: ["Home Accessories & Decor", "Flooring", "Wallpaper"],
    images: [
      "/shops images/Home_Plus/DSCF2183-1.JPG",
      "/shops images/Home_Plus/IMG-20250701-WA0020.jpg",
      "/shops images/Home_Plus/IMG-20250701-WA0023.jpg",
      "/shops images/Home_Plus/IMG-20250701-WA0028.jpg",
    ],
  },
  {
    floor: "Ground Floor",
    logo: "/logos/Verdera_Original Logo.webp",
    phone: ["00201066433666"],
    email: "example@mail.com",
    name: "Verdera",
    facebook: "",
    instagram: "",
    category: ["Artificial Plants & Pots", "Home Accessories & Decor"],
    images: [
      "/shops images/Verdera/DSCF0390.JPG",
      "/shops images/Verdera/DSCF0285.JPG",
      "/shops images/Verdera/DSCF0402.JPG",
      "/shops images/Verdera/DSCF0271.JPG",
    ],
  },
  {
    floor: "Second Floor",
    logo: "/logos/SMART-Shutter-Final-Logo-copy.webp",
    phone: ["01280646818"],
    email: "example@mail.com",
    name: "Smart Shutter",
    facebook: "https://www.facebook.com/SmartShutterEg/",
    instagram: "",
    category: ["Doors & Windows", "Shutters & Motorized Gates"],
    images: [
      "/shops images/Smart_Shutter/Bathroom Blinds 2.jpg",
      "/shops images/Smart_Shutter/Flagstaff Hill 2.jpg",
      "/shops images/Smart_Shutter/Sliding.jpg",
      "/shops images/Smart_Shutter/Blackout phifer 2.jpg",
    ],
  },
  {
    floor: "Ground Floor",
    logo: "/logos/Hanimex_logo_black.webp",
    phone: ["01225555003", "0238260068", "01140493330"],
    email: "example@mail.com",
    name: "Hanimex",
    facebook: "https://www.facebook.com/hanimex.net/?locale=ar_AR",
    instagram: "",
    category: [
      "Kitchens",
      "Home Accessories & Decor",
      "Dressing Rooms",
      "Office Furniture",
      "Lighting",
      "hardware",
      "Bathrooms accessories",
      "Artificial Plants & Pots",
      "Flooring",
      "Outdoor Furniture",
    ],
    images: [
      "/shops images/Hanimex/6a6a6eb5fa6ddf0e162157472cf9a60e.jpg",
      "/shops images/Hanimex/52967-ek9298-kitchen-shot.png",
      "/shops images/Hanimex/Divano.jpg",
      "/shops images/Hanimex/LUCE 02 ambientata.jpg",
    ],
  },
  {
    floor: "First Floor",
    logo: "/logos/Divano_Artboard 1.webp",
    phone: ["01068820413"],
    email: "example@mail.com",
    name: "Divano",
    facebook: "",
    instagram: "https://www.instagram.com/divano.home.furniture/?hl=ar",
    category: ["Modern Furniture", "Dressing Rooms"],
    images: [
      "/shops images/Divano/9cd36757ffcdf483cc9146395995b279.jpg",
      "/shops images/Divano/Big Round.jpg",
      "/shops images/Divano/Curve (3).jpg",
      "/shops images/Divano/Florida U Shape.jpg",
    ],
  },
  {
    floor: "First Floor",
    logo: "/logos/fagor copy.webp",
    phone: ["01227237666"],
    email: "example@mail.com",
    name: "Fagor",
    facebook: "",
    instagram: "",
    category: ["Kitchen Appliances", "Home Appliances"],
    images: [
      "/shops images/Fagor/B0293GCL.png",
      "/shops images/Fagor/BO243EIE.png",
      "/shops images/Fagor/BO243YQL.png",
      "/shops images/Fagor/BO243YRL.png",
    ],
  },
  {
    floor: "First Floor",
    logo: "/logos/Zahran_Logo_English copy.webp",
    phone: ["02-38260079"],
    email: "example@mail.com",
    name: "Zahran",
    facebook: "https://www.facebook.com/zahranstoreofficial/?locale=ar_AR",
    instagram: "https://www.instagram.com/zahranstores/?hl=ar",
    category: ["Kitchenware", "Home Appliances"],
    images: [
      "/shops images/zahran tefal/6pc-set-house-miniature-metal-kitchenware.jpg",
      "/shops images/zahran tefal/41ubejAduiL.jpg",
      "/shops images/zahran tefal/988db4170874dba4a7e4d7805ecdaca0.jpg",
      "/shops images/zahran tefal/item_XL_23671938_34023295.jpg",
    ],
  },
  {
    floor: "First Floor",
    logo: "/logos/Raif Tex_Artboard 1.webp",
    phone: ["01029505398"],
    email: "example@mail.com",
    name: "Raif",
    facebook: "https://www.facebook.com/raiftextile/?locale=ar_AR",
    instagram: "https://www.instagram.com/raiftextile/?hl=ar",
    category: ["Fabric & Curtains"],
    images: [
      "/shops images/Raif/DSC06654.jpg",
      "/shops images/Raif/DSC06664.jpg",
      "/shops images/Raif/DSC06665.jpg",
      "/shops images/Raif/DSC06658.jpg",
    ],
  },
  {
    floor: "First Floor",
    logo: "/logos/velour-de-jene-logo-FINAL--2.webp",
    phone: ["01115851266"],
    email: "example@mail.com",
    name: "Velour De Gene",
    facebook: "",
    instagram: "https://www.instagram.com/reel/C0eosmOM8bU/",
    category: ["Fabric & Curtains"],
    images: [
      "/shops images/Velour De Gene/WhatsApp Image 2024-12-02 at 6.35.27 PM (2).jpeg",
      "/shops images/Velour De Gene/WhatsApp Image 2024-12-02 at 6.35.27 PM.jpeg",
      "/shops images/Velour De Gene/WhatsApp Image 2024-12-02 at 6.35.28 PM (2).jpeg",
      "/shops images/Velour De Gene/WhatsApp Image 2024-12-02 at 3.56.21 PM.jpeg",
    ],
  },
  {
    floor: "First Floor",
    logo: "/logos/Lumberjack-logo_vector.webp",
    phone: ["01104369689"],
    email: "example@mail.com",
    name: "Lumberjack",
    facebook: "https://www.facebook.com/thelumberjack.eg/?locale=ar_AR",
    instagram: "",
    category: ["Modern Furniture", "Outdoor Furniture"],
    images: [
      "/shops images/Lumberjack/The Lumberjack 17-7-2022 (8).jpg",
      "/shops images/Lumberjack/The Lumberjack 17-7-2022 (9).jpg",
      "/shops images/Lumberjack/The Lumberjack 17-7-2022 (10).jpg",
      "/shops images/Lumberjack/WhatsApp Image 2022-12-27 at 3.27.27 AM (1)IMG_20240701_120938.jpeg",
    ],
  },
  {
    floor: "First Floor",
    logo: "/logos/Cube.webp",
    phone: ["01201111451"],
    email: "example@mail.com",
    name: "Cube Furniture",
    facebook: "https://www.facebook.com/cubehomefurniture/",
    instagram: "https://www.instagram.com/cube.furniture/?hl=ar",
    category: ["Modern Furniture"],
    images: [
      "/shops images/Cube Furniture/CUBE FURNITURE/269.jpeg",
      "/shops images/Cube Furniture/CUBE FURNITURE/29.jpg",
      "/shops images/Cube Furniture/CUBE FURNITURE/BLUES.jpg",
      "/shops images/Cube Furniture/CUBE FURNITURE/Daimond.jpg",
    ],
  },
  {
    floor: "First Floor",
    logo: "/logos/Comfort Home collection (2).webp",
    phone: ["01110505035"],
    email: "example@mail.com",
    name: "Comfort home",
    facebook: "https://www.facebook.com/comfort.hc/?locale=ar_AR",
    instagram: "https://www.instagram.com/comforthomecollection/?hl=ar",
    category: ["Mattresses"],
    images: [
      "/shops images/Comfort Home/Comfort 28-6-2010065629 copy.jpg",
      "/shops images/Comfort Home/Comfort 28-6-2010065713.jpg",
      "/shops images/Comfort Home/comfort cam2 28-6-2010-024822.jpg",
      "/shops images/Comfort Home/Comfort 28-6-2010065629 copy.jpg",
    ],
  },
  {
    floor: "Second Floor",
    logo: "/logos/Artboard 1 copy.webp",
    phone: ["0109666146"],
    email: "example@mail.com",
    name: "Bed In Home",
    facebook: "https://www.facebook.com/BedNHome/?locale=ar_AR",
    instagram: "https://www.instagram.com/bednhome1/?hl=ar",
    category: ["Bed Linens", "Mattresses"],
    images: [
      "/shops images/Bed N Home/duvet (2).jpg",
      "/shops images/Bed N Home/mattress topper (3).jpg",
      "/shops images/Bed N Home/A1PJapR7dGL.jpg",
      "/shops images/Bed N Home/Pillow (2).jpeg",
    ],
  },
  {
    floor: "First Floor",
    logo: "/logos/Malina.webp",
    phone: ["01156156020", "01021943886"],
    email: "example@mail.com",
    name: "Malina",
    facebook: "https://www.facebook.com/malinafurniture/",
    instagram: "",
    category: ["Home Accessories & Decor", "Outdoor Furniture"],
    images: [
      "/shops images/Malina/WhatsApp Image 2025-06-23 at 3.23.06 PM.jpeg",
      "/shops images/Malina/WhatsApp Image 2025-06-23 at 3.23.07 PM (1).jpeg",
      "/shops images/Malina/WhatsApp Image 2025-06-23 at 3.23.07 PM (2).jpeg",
      "/shops images/Malina/WhatsApp Image 2025-06-23 at 3.23.09 PM.jpeg",
    ],
  },
  {
    floor: "First Floor",
    logo: "/logos/selim.png",
    phone: ["01069564959"],
    email: "example@mail.com",
    name: "Naguib Selim",
    facebook: "",
    instagram: "",
    category: ["Fabric & Curtains"],
    images: [
      "/shops images/Nagib Sliem/WhatsApp Image 2022-11-07 at 1.42.56 AM.jpeg",
      "/shops images/Nagib Sliem/_DSC925000cvvvfxvdddddvvvvvvv.jpg",
      "/shops images/Nagib Sliem/_DSC925000cvvvf.jpg",
      "/shops images/Nagib Sliem/_DSC925000cvvvfxvd.jpg",
    ],
  },
  {
    floor: "First Floor",
    logo: "/logos/Malek-New-Logo-2.webp",
    phone: ["01015157998"],
    email: "example@mail.com",
    name: "Malek",
    facebook: "",
    instagram: "",
    category: ["Bed Linens", "Dressing Rooms"],
    images: [
      "/shops images/malek/2.png",
      "/shops images/malek/4.png",
      "/shops images/malek/16.png",
      "/shops images/malek/38.PNG",
    ],
  },
  {
    floor: "First Floor",
    logo: "/logos/T-Track.webp",
    phone: ["01151404600"],
    email: "example@mail.com",
    name: "T-Track",
    facebook:
      "https://www.facebook.com/p/TTrack-Pvc-U-10/0067771684991/?locale=ar_AR",
    instagram: "https://www.instagram.com/track.gmbh/",
    category: ["Doors & Windows", "Shutters & Motorized Gates"],
    images: [
      "/shops images/TTrack/5.jpg",
      "/shops images/TTrack/IMG-20180130-WA0011.jpg",
      "/shops images/TTrack/6.jpg",
      "/shops images/TTrack/1 (1).jpg",
    ],
  },
  {
    floor: "First Floor",
    logo: "/logos/Asia-copy.webp",
    phone: ["02-38260097", "01066677755"],
    email: "example@mail.com",
    name: "Asia Furniture",
    facebook: "https://www.facebook.com/asiafurniturestore/",
    instagram: "https://www.instagram.com/asiafurniturestore/?hl=ar",
    category: ["Outdoor Furniture"],
    images: [
      "/shops images/Asia_Furniture/IMG_8146.jpg",
      "/shops images/Asia_Furniture/IMG_8402.jpg",
      "/shops images/Asia_Furniture/IMG_7961.jpg",
      "/shops images/Asia_Furniture/IMG_8245.jpg",
    ],
  },
  {
    floor: "First Floor",
    logo: "/logos/kian-logo.webp",
    phone: ["01227342555"],
    email: "example@mail.com",
    name: "Kian",
    facebook: "https://www.facebook.com/kianegypt",
    instagram: "https://www.instagram.com/kianegypt/",
    category: ["Outdoor Furniture", "Home Accessories & Decor"],
    images: [
      "/shops images/Kian/WhatsApp Image 2025-03-23 at 10.56.45 AM.jpeg",
      "/shops images/Kian/WhatsApp Image 2025-03-23 at 10.56.45 AM (2).jpeg",
      "/shops images/Kian/WhatsApp Image 2025-03-23 at 10.56.45 AM (1).jpeg",
    ],
  },
  {
    floor: "First Floor",
    logo: "/logos/Comfort-Sleep-Logo.webp",
    phone: ["01148559991"],
    email: "example@mail.com",
    name: "Comfort Sleep",
    facebook: "https://www.facebook.com/comfortsleepegypt/",
    instagram: "",
    category: ["Mattresses", "Bed Linens"],
    images: [
      "/shops images/Comfort_sleep/Naxos (2).jpg",
      "/shops images/Comfort_sleep/elise-pink-performance-velvet-channel-tufted-twin-bed-by-modway-16.jpg",
      "/shops images/Comfort_sleep/hybrid_mattress.png",
      "/shops images/Comfort_sleep/Bodema.jpg",
    ],
  },
  {
    floor: "Second Floor",
    logo: "/logos/Fida-Home-Gte-Vinyl.webp",
    phone: ["01147902010"],
    email: "example@mail.com",
    name: "Fida Home",
    facebook: "https://www.facebook.com/fidahome.egypt/",
    instagram: "",
    category: ["Modern Furniture"],
    images: [
      "/shops images/Fida Home/Viola.jpeg",
      "/shops images/Fida Home/Linia .jpeg",
      "/shops images/Fida Home/Conic Dining .jpg",
      "/shops images/Fida Home/Celine master& Teen Bedroom (1).jpg",
    ],
  },
  {
    floor: "Second Floor",
    logo: "/logos/Capital-Design.webp",
    phone: ["01026444366"],
    email: "example@mail.com",
    name: "Capital Design",
    facebook: "https://www.facebook.com/capitaldesignfurniture/",
    instagram: "https://www.instagram.com/capital.design.eg/",
    category: ["Modern Furniture"],
    images: [
      "/shops images/Capital Design/Capital Design_286 copy.jpg",
      "/shops images/Capital Design/9.jpg",
      "/shops images/Capital Design/7.jpg",
      "/shops images/Capital Design/6.jpg",
    ],
  },
  {
    floor: "First Floor",
    logo: "/logos/CAJA Text logo.webp",
    phone: ["01096660844", "01027003500"],
    email: "example@mail.com",
    name: "Caja",
    facebook: "https://www.facebook.com/CAJA.furniture/?locale=ar_AR",
    instagram: "https://www.instagram.com/caja.furniture/?hl=ar",
    category: ["Kitchens", "Dressing Rooms"],
    images: [
      "/shops images/Caja/Caja (2).jpg",
      "/shops images/Caja/Caja (9).jpg",
      "/shops images/Caja/Caja 11-5-2022 (2).jpg",
      "/shops images/Caja/Caja 11-5-2022 (5).jpg",
    ],
  },
  {
    floor: "Second Floor",
    logo: "/logos/Doortech-New-Logo-2023-3.webp",
    phone: ["01283989041"],
    email: "example@mail.com",
    name: "Door Teck",
    facebook: "https://www.facebook.com/doortech.egy/?locale=ar_AR",
    instagram: "",
    category: ["Doors & Windows"],
    images: [
      "/shops images/doortech/DT -Model -12- CPL- LK48 (1).JPG",
      "/shops images/doortech/DT-Model-17-MASSIVE OAK( U ).JPG",
      "/shops images/doortech/DT -Model -13- CPL- LR39.JPG",
      "/shops images/doortech/DT-Model-24- OKOUME– RANDOM Boxes.JPG",
    ],
  },
  {
    floor: "First Floor",
    logo: "/logos/RADWAN-Mardini-NEW.webp",
    phone: ["01009218540", "01111598448"],
    email: "example@mail.com",
    name: "Radwan Mardini",
    facebook: "https://www.facebook.com/RadwanMardini/?locale=ar_AR",
    instagram: "",
    category: ["Fabric & Curtains"],
    images: [
      "/shops images/Radwan Mardini/Calenders Mardini 299.jpg",
      "/shops images/Radwan Mardini/Calenders Mardini 308.jpg",
      "/shops images/Radwan Mardini/Calenders Mardini 309.jpg",
      "/shops images/Radwan Mardini/chance 01.jpg",
    ],
  },
  {
    floor: "Second Floor",
    logo: "/logos/innova-logo--2.webp",
    phone: ["01101315752"],
    email: "example@mail.com",
    name: "Innova",
    facebook: "",
    instagram: "",
    category: ["Modern Furniture"],
    images: [
      "/shops images/Innova/11 copy.jpg",
      "/shops images/Innova/8.jpg",
      "/shops images/Innova/8 copy (1).jpg",
      "/shops images/Innova/7 copy.jpg",
    ],
  },
  {
    floor: "Ground Floor ",
    logo: "/logos/values.png",
    phone: ["01090709999"],
    email: "example@mail.com",
    name: "Values Home",
    facebook: "https://www.facebook.com/VALUESdesign/?locale=ar_AR",
    instagram: "",
    category: ["Modern Furniture"],
    images: [
      "/shops images/Values/values 5.jpg",
      "/shops images/Values/values 4.jpg",
      "/shops images/Values/Values 3.jpg",
      "/shops images/Values/Values 2.jpg",
    ],
  },
  {
    floor: "First Floor",
    logo: "/logos/artynova.png",
    phone: ["01207300038", "01121554224"],
    email: "example@mail.com",
    name: "Artynova",
    facebook: "https://www.facebook.com/ArtynovaFurniture/?locale=ar_AR",
    instagram: "https://www.instagram.com/artynovafurniture/?hl=ar",
    category: ["Kitchens", "Dressing Rooms"],
    images: [
      "/shops images/ArtyNova/WhatsApp Image 2022-01-31 at 4.18.29 PM (2).jpeg",
      "/shops images/ArtyNova/WhatsApp Image 2022-01-31 at 4.18.29 PM (1).jpeg",
      "/shops images/ArtyNova/WhatsApp Image 2022-01-31 at 4.18.28 PM.jpeg",
      "/shops images/ArtyNova/WhatsApp Image 2022-01-31 at 4.18.28 PM (2).jpeg",
    ],
  },
  {
    floor: "First Floor",
    logo: "/logos/spring-copy.webp",
    phone: ["01129221244", "0112922255"],
    email: "example@mail.com",
    name: "Spring Air",
    facebook: "https://www.facebook.com/SpringAirEgypt/?locale=ar_AR",
    instagram: "",
    category: ["Mattresses"],
    images: [
      "/shops images/Spring_Air/02 Visco Pedic.jpg",
      "/shops images/Spring_Air/12004011_984916538196017_8881610200908736363_n.jpg",
      "/shops images/Spring_Air/02 American Spirit.jpg",
      "/shops images/Spring_Air/01  Honey Moon_2 (1).jpg",
    ],
  },
  {
    floor: "Second Floor",
    logo: "/logos/Alf-Italia.webp",
    phone: ["19744", "01210776664"],
    email: "example@mail.com",
    name: "ALF Italia",
    facebook: "",
    instagram: "",
    category: ["Modern Furniture"],
    images: [
      "/shops images/Alf Italia/Belpasso pag 28 29.jpg",
      "/shops images/Alf Italia/Claire pag 6 7.jpg",
      "/shops images/Alf Italia/Jupiter pag 2 3.jpg",
      "/shops images/Alf Italia/Novecento pag 6 7.jpg",
    ],
  },
  {
    floor: "Second Floor",
    logo: "/logos/Natuzzi-Edition.webp",
    phone: ["19744", "01270266679"],
    email: "example@mail.com",
    name: "Natuzzi",
    facebook: "",
    instagram: "https://www.instagram.com/natuzziegypt/",
    category: ["Modern Furniture"],
    images: [
      "/shops images/Natuzzi Editions/c239 1.jpg",
      "/shops images/Natuzzi Editions/c240 1.jpg",
      "/shops images/Natuzzi Editions/c260 2.jpg",
      "/shops images/Natuzzi Editions/LE12 PARIGI 1.jpeg",
    ],
  },
  {
    floor: "Ground Floor Floor",
    logo: "/logos/vevian final logo white background.webp",
    phone: ["01550140557", "01555108015"],
    email: "example@mail.com",
    name: "Vevian",
    facebook: "https://www.facebook.com/people/Drobina/100089809546351/",
    instagram: "",
    category: ["Kitchenware"],
    images: [
      "/shops images/Vevian/image00054.jpeg",
      "/shops images/Vevian/image00027.jpeg",
      "/shops images/Vevian/image00019.jpeg",
      "/shops images/Vevian/image00054.jpeg",
    ],
  },
  {
    floor: "First Floor",
    logo: "/logos/Broderie-Logo.png",
    phone: ["00201001123021"],
    email: "example@mail.com",
    name: "Broderie",
    facebook: "https://www.facebook.com/BroderieTex/",
    instagram: "https://www.instagram.com/broderie.textiles/",
    category: ["Fabric & Curtains"],
    images: [
      "/shops images/Broderie/WhatsApp Image 2023-12-13 at 12.00.20 PM.jpeg",
      "/shops images/Broderie/6F4A2992-.jpg",
      "/shops images/Broderie/6F4A2978-.jpg",
      "/shops images/Broderie/6F4A2966-.jpg",
    ],
  },
  {
    floor: "Second Floor",
    logo: "/logos/Elara Logo-06.webp",
    phone: ["00201011777314"],
    email: "example@mail.com",
    name: "Elara",
    facebook: "",
    instagram: "https://www.instagram.com/elara.furniture/?hl=ar",
    category: ["Modern furniture"],
    images: [
      "/shops images/Elara/IMG_3542.JPG",
      "/shops images/Elara/IMG_3541.JPG",
      "/shops images/Elara/IMG_3540.JPG",
      "/shops images/Elara/IMG_3539.JPG",
    ],
  },
  {
    floor: "Ground Floor",
    logo: "/logos/Only-Tables.webp",
    phone: ["0112 7206 763 0103 0266 007 "],
    name: "Only Tables",
    facebook: "https://www.facebook.com/p/Only-Tables-1000 64522032551/",
    category: ["Home Accessories & Decor"],
    images: [
      "/shops images/Only_Tables/IMG_6046_Final_G.jpg",
      "/shops images/Only_Tables/IMG_6064_Final_G.jpg",
      "/shops images/Only_Tables/IMG_6083_Final_G.jpg",
      "/shops images/Only_Tables/IMG_6010.JPG",
    ],
  },
  {
    floor: "Ground Floor",
    logo: "/logos/Glass Style copy.png",
    phone: ["0112 7206 763 0103 0266 007 "],
    name: "Glass Style",
    facebook: "https://www.facebook.com/GlassStyle.walidonsy/?locale=ar_AR",
    category: ["Home Accessories & Decor", "Hand Made"],
    images: [
      "/shops images/Glass_Style/52557708_10157160847242853_2891176622784774144_n.jpg",
      "/shops images/Glass_Style/22228419_1458526250897727_9082128643932463720_n.jpg",
      "/shops images/Glass_Style/16.jpg",
      "/shops images/Glass_Style/15.jpg",
    ],
  },
];
