import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import Header from "../components/Header";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "HC Furniture Mall",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` ${inter.variable} antialiased bg-background`}>
        <Header />
        <div className="pt-[56px] md:pt-0">
          <main className="min-h-screen">{children}</main>
        </div>
        <Footer /> 
      </body>
    </html>
  );
}
